export {VoipDomain} from './voip-domain.mariadb.entity'
export {VoipSubscriber} from './voip-subscriber.mariadb.entity'
export {XmlGroup} from './xml-group.mariadb.entity'
export {XmlHost} from './xml-host.mariadb.entity'
export {XmlQueue} from './xml-queue.mariadb.entity'
