export function getErrorCodeByTitle(messageTitle): number {
    return +Object.keys(ErrorCodes).find(key => ErrorCodes[key] === messageTitle)
}

const ErrorCodes: { [id: number] : string} = {
    1000: "PERMISSION_DENIED",
    1001: "DELETE_OWN_USER",
    1002: "INVALID_USER_ROLE",
    1003: "CHANGE_OWN_PROPERTY",
    1004: "DUPLICATE_ENTRY",
    1005: "DELETE_CUSTOMERCONTACT",
    1006: "RESELLER_ID_SYSTEMCONTACTS",
    1007: "INVALID_RESELLER_ID",
    1008: "CONTRACT_EXISTS",
    1009: "NAME_EXISTS",
    1010: "CONTRACT_NOT_FOUND",
    1011: "CONTRACT_INVALID_LINK",
    1012: "RESELLER_SET_ID_FORBIDDEN",
    1013: "CHANGE_UNASSOCIATED_FORBIDDEN",
    1014: "RESELLER_INVALID_ID",
    1015: "RESELLER_UNDEFINED_ID",
    1016: "RESELLER_CREATE_INVALID_ASSOCIATION",
    1017: "RESELLER_UPDATE_INVALID_ASSOCIATION",
    1018: "FILES_LIMIT_REACHED",
    1019: "QUOTA_EXCEEDED",
    1020: "DOMAIN_DOES_NOT_BELONG_TO_RESELLER",
    1021: "CONTACT_STILL_IN_USE",
    1022: "DELETE_SYSTEMCONTACT",
    1023: "INVALID_TYPE",
    1024: "INVALID_CONTACT_ID",
    1025: "INVALID_SYSTEM_CONTACT",
    1026: "DELETE_SPECIAL_USER",
    1027: "EXPAND_OBJECT_FAILED"
}
