export const MessageDescriptionsEN: { [id: string] : any} = {
    PERMISSION_DENIED: 'Permission denied',
    DELETE_OWN_USER: 'Cannot delete own user',
    INVALID_USER_ROLE: 'Invalid user role',
    CHANGE_OWN_PROPERTY: 'Cannot change own property',
    DUPLICATE_ENTRY: 'Duplicate entry',
    DELETE_CUSTOMERCONTACT: 'Cannot delete customercontact',
    RESELLER_ID_SYSTEMCONTACTS: 'reseller_id not allowed on systemcontacts',
    INVALID_RESELLER_ID: 'Invalid reseller_id',
    CONTRACT_EXISTS: 'invalid \'contract_id\', reseller with Messages contract already exists',
    NAME_EXISTS: 'invalid \'name\', reseller with Messages name already exists',
    CONTRACT_NOT_FOUND: 'Invalid \'contract_id\'',
    CONTRACT_INVALID_LINK: 'Invalid \'contract_id\', linking to a customer contact',
    CHANGE_ID_FORBIDDEN: 'Changing the reseller ID is not allowed',
    RESELLER_SET_ID_FORBIDDEN: 'Cannot set the reseller Id if it was unset before',
    CHANGE_UNASSOCIATED_FORBIDDEN: 'Updating items not associated with a reseller is not allowed',
    RESELLER_INVALID_ID: 'Reseller ID other than the user\'s reseller ID is not allowed',
    RESELLER_UNDEFINED_ID: 'Undefined reseller ID is not allowed',
    RESELLER_CREATE_INVALID_ASSOCIATION: 'Creating items associated with a reseller is allowed for admin and reseller users only',
    RESELLER_UPDATE_INVALID_ASSOCIATION: 'Updating items associated with a reseller is allowed for admin and reseller users only',
    FILES_LIMIT_REACHED: 'Files limit reached',
    QUOTA_EXCEEDED: 'Quota exceeded',
    DOMAIN_DOES_NOT_BELONG_TO_RESELLER: 'domain does not belong to reseller',
    CONTACT_STILL_IN_USE: 'Contact is still in use',
    DELETE_SYSTEMCONTACT: 'Cannot delete systemcontact',
    INVALID_TYPE: 'invalid \"type\"',
    INVALID_CONTACT_ID: 'invalid contact_id',
    INVALID_SYSTEM_CONTACT: 'The contact_id is not a valid ngcp:systemcontacts item, but an ngcp:customercontacts item',
    DELETE_SPECIAL_USER: 'Cannot delete special user',
    EXPAND_OBJECT_IMPOSSIBLE: (str: string) => `Expanding ${str} not allowed or impossible`,
    EXPAND_OBJECT_FAILED: (str: string) => `Cannot expand field ${str}`,
    DOMAIN_ALREADY_EXISTS: (str: string) => `domain ${str} already exists`,
    UNKNOWN_ROLE: (str: string) => `Unknown role ${str}`,
    VALIDATION_FAILED_UNSUPPORTED_ID: 'Validation failed (unsupported :id format)'
}
